### ISSUE TITLE
Long compiler startup time impacting TDD cycles

### ISSUE THREAD

**Issue by frankdugan3** [bartblast/hologram#254]
When the compiler starts up, it seems to take an average of 5+ seconds on my machine.

```sh
07:45:06.383 [info] Hologram: compiler started
07:45:12.522 [info] Hologram: compiler finished
```

Briefly examining the compiler code, I'm assuming this has to do with various JS package checks and similar items. For starting the app once for a dev server, it's not a big deal since it only happens at startup. But when doing TDD using `mix test.watch`, it adds quite a pause to my tests which normally take ~1 second.

Is there configuration specifically for the `:test` env, to help alleviate this problem?

**Comment by bartblast** [comment]
Hey @frankdugan3, there's no configuration option for this yet, but it should be easy to solve this problem. How urgent is this for your workflow?

**Comment by frankdugan3** [comment]
Not urgent, just putting this on the radar for the future.

**Comment by treeman** [comment]
I did a simple workaround like so:

```elixir
  def project do
    [
      compilers: compilers(),
      # ...
    ]
  end


  def compilers do
    if Mix.env() != :test do
      [:phoenix_live_view, :hologram] ++ Mix.compilers()
    else
      [:phoenix_live_view] ++ Mix.compilers()
    end
  end
```

Not the prettiest but as I don't test hologram code directly it works for now. Note that you have to compile the code at least once but after that you can ignore the compiler during testing.

**Comment by bartblast** [comment]
Yep, should work as a workaround if you don't need to start the server for feature tests. I believe the final solution should be something along these lines related to test setup, need to look at this when the Hologram standalone mode is released later this week.

**Comment by dillonoconnor** [comment]
FWIW this is severely impacting my development workflow while trying to run `ash.codegen`, `ash.migrate`, `ash.reset`, etc. (in addition to test and server start). It sometimes takes 10 extra seconds for each command.

**Comment by sodapopcan** [comment]
Gonna add my voice as this is a bit of a problem.  @treeman's solution works for domain layer tests but obviously can't work for features tests and I like to TDD all my views.

I have some free time these days so if there is anything I can do to help out, let me know.

**Comment by treeman** [comment]
For me, this is the number one issue with Hologram as it really impacts the developer experience. The test workaround I've used before is insufficient as noted in previous comments (running commands such as `ash.codegen` and that we'd really like to test Hologram parts of the app).

**Comment by bartblast** [comment]
Hey everyone, I'm working on a solution for this. The plan:

- The Hologram compiler will be skipped by default in dev and test environments unless a `HOLOGRAM_COMPILE` env var is set
- A new `mix holo` task will set this env var underneath and start the dev server (replacing `mix phx.server` for Hologram apps)
- Live reload will continue to trigger recompilation on file changes as before

This means `mix test`, `ash.codegen`, `ash.migrate` etc. will no longer pay the compiler startup cost.

The `HOLOGRAM_COMPILE` env var is also available directly, so anyone can use it to build custom mix tasks or workflows that need the compiler (e.g. `HOLOGRAM_COMPILE=1 mix my_custom_task`).

@sodapopcan regarding TDD'ing views - Hologram pages and components are regular Elixir modules, so you can unit test them without the Hologram compiler running. The compiler is only needed to produce JS bundles and run some compile-time checks (e.g. verifying pages have routes and layouts defined) - these checks could also be moved to regular Elixir compilation in the future.

Does anyone see any issues with this approach?

**Comment by sodapopcan** [comment]
I forgot to follow up but I've noticed that even after disabling the hologram compiler, there is a still a noticeable lag in compilation time.  Much smaller, of course, but still very noticeable.  It went away entirely when I tried removing Hologram.  I can give more info if this is not expected.

**Comment by bartblast** [comment]
This has been addressed in #767 and will be released in v0.9.0.

One change from my earlier comment: the env var is now `HOLOGRAM_START` instead of `HOLOGRAM_COMPILE`. Skipping just the compiler wasn't enough - the Hologram application also needs to skip starting its supervisor children (registries, live reload), otherwise they would fail trying to load compiler artifacts that don't exist. So the env var controls the full Hologram stack, not just compilation.

### Starting the dev server

Use `mix holo` instead of `mix phx.server`:

```
mix holo
```

or with IEx:

```
iex -S mix holo
```

This sets `HOLOGRAM_START=1` underneath and starts the application with Hologram fully enabled.

### Running tests

Regular tests work as before - just faster:

```
mix test
```

The Hologram compiler and application children are automatically skipped.

### Running feature/browser tests

If you have tests that need the full Hologram stack (e.g. browser tests with Wallaby), add this to your `test_helper.exs`:

```elixir
Hologram.Test.setup()
```

This runs the compiler, restarts the Hologram application with the full supervisor tree, and handles everything automatically. If you only want it for specific test runs, you can use ExUnit tags, for example:

```elixir
# test_helper.exs
if "--only" in System.argv() and "feature" in System.argv() do
  Hologram.Test.setup()
end
```

Then tag your feature tests with `@tag :feature` and run them with:

```
mix test --only feature
```

### Production and other environments

`HOLOGRAM_START` is only relevant for dev and test. In production (and any other environment like staging), Hologram starts fully automatically - no env var or configuration changes needed.

### Using the env var directly

The `HOLOGRAM_START` env var is also available for custom workflows:

```
HOLOGRAM_START=1 mix my_custom_task
```

**Comment by bartblast** [comment]
@sodapopcan regarding the lag you noticed even after disabling the compiler - this PR addresses the originally reported problem (compiler running during mix tasks). If you'd like to check whether the lag is still there, you can point to the merge commit before the v0.9.0 release:

```elixir
{:hologram, git: "https://github.com/bartblast/hologram.git", ref: "fb99ee867d6a0ae70615a7d874bbdf8d170039ae"}
```

If you still experience any issues, please open a new issue with details and I'll look into it.

**Comment by sodapopcan** [comment]
Dude, you're the best!  This works great.  It feels like the delay might still be there but it seems less?  The repo I've been testing everything in is a mess and it's hard for me to go back, but how it is now is perfectly acceptable.

**Comment by sodapopcan** [comment]
I'm actually still getting long comp times in dev.  I'm still gathering data, but in a project with Ash (and I'm not sure Ash is the culprit) which is _very_ greenfield, it takes around 5 seconds every time I make a change to a `Page`.  I made a fresh project with just Phoenix and Hologram and it's nowhere near as slow but still not instant, like around 1 second I'd say.  I guess this is known?

**Comment by bartblast** [comment]
@sodapopcan Did v0.8.3 fix this for you?

**Comment by sodapopcan** [comment]
I'm on `0.8.3` but this doesn't appear to have the changes talked about here.  `mix holo` is unavailable and `mix test` still starts the compiler.

```shell
 $ mix deps | grep holo    
* hologram 0.8.3 (Hex package) (mix)
  locked at 0.8.3 (hologram) 64a2eb21
```

**Comment by bartblast** [comment]
@sodapopcan Current dev head (84b59fe) has all recent changes with all checks green.
